title: Varodonaire
author: Alvaro Mattus Donaire
description: Alvaradas


remote_theme: dieghernan/chulapa



include:
  - .htaccess
  - _pages

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
